apiVersion: v1
kind: Service
metadata:
  name: expenses-web
  labels:
    app: expenses-web
spec:
  type: LoadBalancer
  selector:
    app: expenses-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
