version: "3.9"

services:
  expenses-web:
    build:
      context: ../../apps/expenses
    environment:
      EXPENSES_DATABASE: sqlite:////app/instance/expenses.db
      EXPENSES_UPLOADS: /app/instance/uploads
      EXPENSES_SECRET_KEY: dev-secret
    volumes:
      - ../../apps/expenses/instance:/app/instance
    ports:
      - "8080:8000"

  quote-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: quote_tool
      POSTGRES_PASSWORD: quote_tool
      POSTGRES_DB: quote_tool
    volumes:
      - quote-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quote_tool"]
      interval: 10s
      timeout: 5s
      retries: 5

  quote-tool:
    build:
      context: ../../apps/quote-tool
    environment:
      FLASK_APP: flask_app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://quote_tool:quote_tool@quote-db:5432/quote_tool
    depends_on:
      quote-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - ../../apps/quote-tool:/app

  hana-inventory:
    build:
      context: ../../apps/hana-inventory
    command: flask run --host=0.0.0.0 --port=8000
    environment:
      FLASK_APP: app:create_app
      FLASK_ENV: development
    ports:
      - "8001:8000"
    volumes:
      - ../../apps/hana-inventory:/app

volumes:
  quote-data:
