services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes","--save","", "--stop-writes-on-bgsave-error","no"]
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  quote_tool:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URL}
      CACHE_TYPE: redis
      CACHE_REDIS_URL: ${CACHE_REDIS_URL}
      RATELIMIT_STORAGE_URI: ${RATELIMIT_STORAGE_URI}
    ports:
      - "8000:8000"
