services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-quote_tool}
      POSTGRES_USER: ${POSTGRES_USER:-quote_tool}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-quote_tool}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes","--save","", "--stop-writes-on-bgsave-error","no"]
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

  quote_tool:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      SECRET_KEY: ${SECRET_KEY:-}
      DATABASE_URL: ${DATABASE_URL:-}
      SQLALCHEMY_DATABASE_URI: ${DATABASE_URL:-}
      CACHE_TYPE: redis
      CACHE_REDIS_URL: ${CACHE_REDIS_URL:-redis://redis:6379/0}
      RATELIMIT_STORAGE_URI: ${RATELIMIT_STORAGE_URI:-redis://redis:6379/1}
    ports:
      - "8000:8000"
