name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python scripts/install_dependencies.py
      - name: Run tests
        env:
          DATABASE_URL: sqlite:///test.db
        run: pytest -q
