name: Quote Tool CI

on:
  push:
    paths:
      - 'apps/quote-tool/**'
      - 'packages/**'
      - '.github/workflows/quote-tool.yml'
  pull_request:
    paths:
      - 'apps/quote-tool/**'
      - 'packages/**'
      - '.github/workflows/quote-tool.yml'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/quote-tool
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black ruff

      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///test.db
        run: pytest
